[package]
name = "qsc_rca"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = { workspace = true }
indenter = { workspace = true }
qsc_data_structures = { path = "../qsc_data_structures" }
qsc_fir = { path = "../qsc_fir" }
qsc_frontend = { path = "../qsc_frontend" }
qsc_lowerer = { path = "../qsc_lowerer" }
rustc-hash = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
qsc = { path = "../qsc" }
qsc_passes = { path = "../qsc_passes" }

[lints]
workspace = true
