[package]
name = "qsc_eval"

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miette = { workspace = true }
ndarray = { workspace = true }
num-bigint = { workspace = true }
num-complex = { workspace = true }
num-traits = { workspace = true }
qdk_simulators =  { path = "../../simulators" }
qsc_data_structures = { path = "../qsc_data_structures" }
qsc_fir = { path = "../qsc_fir" }
qsc_hir = { path = "../qsc_hir" }
qsc_lowerer = { path = "../qsc_lowerer" }
rand =  { workspace = true }
rustc-hash = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
indoc = { workspace = true }
qsc_frontend = { path = "../qsc_frontend" }
qsc_passes = { path = "../qsc_passes" }

[lints]
workspace = true

[lib]
doctest = false
