[package]
name = "qsc_frontend"

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miette = { workspace = true }
qsc_data_structures = { path = "../qsc_data_structures" }
qsc_ast = { path = "../qsc_ast" }
qsc_hir = { path = "../qsc_hir" }
qsc_parse = { path = "../qsc_parse" }
library = { path = "../../../library" }
rustc-hash = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
indoc = { workspace = true }

[lints]
workspace = true

[lib]
doctest = false

[features]
# (Former numeric_promotion feature merged into baseline; feature stanza left for future additions.)
default = []
