[package]
name = "samples_test"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dev-dependencies]
expect-test = { workspace = true }
miette = { workspace = true, "features" = ["fancy"] }
qsc = { path = "../compiler/qsc" }
qsc_project = { path = "../compiler/qsc_project" }

[lints]
workspace = true
