[package]
name = "qsc_passes"

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miette = { workspace = true }
qsc_data_structures = { path = "../qsc_data_structures" }
qsc_eval = { path = "../qsc_eval" }
qsc_fir = { path = "../qsc_fir" }
qsc_frontend = { path = "../qsc_frontend" }
qsc_hir = { path = "../qsc_hir" }
qsc_lowerer = { path = "../qsc_lowerer" }
qsc_rca = { path = "../qsc_rca" }
rustc-hash = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
indoc = { workspace = true }
qsc = { path = "../qsc" }
qsc_eval = { path = "../qsc_eval" }

[lints]
workspace = true

[lib]
doctest = false
