[package]
name = "library"

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dev-dependencies]
indoc = { workspace = true }
num-bigint = { workspace = true }
qsc = { path = "../compiler/qsc" }

[lib]
doctest = false
