[package]
name = "noisy-simulator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.32.5", features = ["rayon"] }
num = "0.4.3"
rand = "0.8.5"
rayon = "1.10.0"
